version: '3'

services:
  ui:
    build: ./ui
    ports:
      - "5000:5000"
    depends_on:
      - ai-backend
    networks:
      - backend-network

  ai-backend:
    build: ./ai-backend
    ports:
      - "5001:5001"
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
