version: '3'

services:
  ui:
    build: ./ui
    ports:
      - "5000:5000"
    depends_on:
      - ai-backend
    environment:
      - AI_BACKEND_URL=http://ai-backend:5001
      - DATA_PATH=/app/data
    volumes:
      - ./data:/app/data
    networks:
      - backend-network

  ai-backend:
    build: ./ai-backend
    ports:
      - "5001:5001"
    environment:
      - DATA_PATH=/app/data
    volumes:
      - ./data:/app/data
    networks:
      - backend-network


networks:
  backend-network:
    driver: bridge
